name: Nethunter Kernel Builder

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git ccache build-essential libncurses-dev \
          flex bison libssl-dev libelf-dev python3 dwarves kmod

      - name: Clone kernel
        run: |
          git clone --depth=1 https://github.com/LineageOS/android_kernel_nubia_sm8450.git kernel
          cd kernel
          git config --global user.name "Your Name"
          git config --global user.email "you@example.com"

      - name: Apply NetHunter patches
        run: |
          cd kernel
          wget https://gitlab.com/kalilinux/nethunter/kernel-nethunter/-/raw/master/patches/5.10-wifi-injection.patch
          patch -p1 < 5.10-wifi-injection.patch

      - name: Configure kernel
        run: |
          cd kernel
          make nubia_sm8450_defconfig
          echo "CONFIG_HID=y" >> .config
          echo "CONFIG_USB_CONFIGFS_F_HID=y" >> .config
          echo "CONFIG_NETFILTER_XT_TARGET_NFQUEUE=y" >> .config

      - name: Build kernel
        run: |
          cd kernel
          make -j$(nproc) CC="ccache gcc"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nethunter-kernel
          path: |
            kernel/arch/arm64/boot/Image.gz-dtb
            kernel/drivers/hid/hid.ko
